export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
export const SHOW_THREE_BTN_ALERT = "SHOW_THREE_BTN_ALERT";
export const HIDE_THREE_BTN_ALERT = "HIDE_THREE_BTN_ALERT";
